# Generated by Django 3.2.9 on 2021-12-05 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, unique=True)),
                ('image', models.ImageField(null=True, upload_to='profile/')),
                ('studentid', models.CharField(max_length=20, null=True, unique=True)),
                ('department', models.CharField(max_length=100, null=True)),
                ('personnel', models.CharField(choices=[('0', '학부생'), ('1', '교수')], default='0', max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
