# Generated by Django 3.2.9 on 2021-11-25 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='message',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='nickname',
            new_name='studentid',
        ),
    ]
