# Generated by Django 3.2.9 on 2021-11-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0003_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='personnel',
            field=models.CharField(choices=[('1', '학부생'), ('2', '교수')], default='1', max_length=5),
        ),
    ]
