# Generated by Django 3.2.9 on 2021-11-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0004_profile_personnel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='personnel',
            field=models.CharField(choices=[('0', '학부생'), ('1', '교수')], default='0', max_length=5),
        ),
    ]
